config/routes.rb
# -*- encoding : utf-8 -*-
Objectbox::Application.routes.draw do
  resources :alerts
  resources :cooking_ingredients
  resources :cooking_recipes do
    resources :cooking_ingredients
  end

  resources :simpletexts
  resources :postits
  resources :boards do
    resources :postits
  end

  resources :users
  resource :session

  match 'boards/:id' => 'boards#update', :method => :post
  match '/search' => 'search#index', :as => :search
  match 'search/:q' => 'search#index'
  match '/logout' => 'sessions#destroy', :as => :logout
  match '/login' => 'sessions#new', :as => :login
  match '/register' => 'users#create', :as => :register
  match '/signup' => 'users#new', :as => :signup
  match '/activate/:activation_code' => 'users#activate', :as => :activate
  match '/myprofile' => 'users#myprofile', :as => :myprofile
  match '/:controller(/:action(/:id))'

  root :to => 'object_collection#index'

end

app/models/cooking_recipe.rb
# -*- encoding : utf-8 -*-
class CookingRecipe < ActiveRecord::Base
  #acts_as_possession

  has_and_belongs_to_many :cooking_ingredients,
                          :join_table => :cooking_recipes_ingredients,
                          :foreign_key => :cooking_recipes_id,
                          :association_foreign_key => :cooking_ingredients_id

  DIFFICULTIES = %w{easy normal difficult complex}

  validates_presence_of :name, :difficult
  validates_inclusion_of :difficult, :in => 0 .. DIFFICULTIES.size - 1

  alias_attribute :ingredients, :cooking_ingredients

  def to_s
    self.name
  end

  def dificult
    DIFFICULTIES[read_attribute(:difficult)] if read_attribute(:difficult)
  end

  def dificult=(difficult)
    difficult = DIFFICULTIES.find_index(difficult) if difficult.is_a? String
    write_attribute :difficult, difficult
  end

  def self.difficulties
    DIFFICULTIES
  end

  def self.icon
    "connoisseur-icon.png"
  end
end

app/controllers/cooking_recipes_controller.rb
# -*- encoding : utf-8 -*-
class CookingRecipesController < ApplicationController
  before_filter :convert_difficult_to_i, :only => [:create, :update]

  # GET /cooking_recipes
  # GET /cooking_recipes.xml
  def index
    @cooking_recipes = CookingRecipe.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @cooking_recipes }
    end
  end

  # GET /cooking_recipes/1
  # GET /cooking_recipes/1.xml
  def show
    @cooking_recipe = CookingRecipe.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @cooking_recipe }
    end
  end

  # GET /cooking_recipes/new
  # GET /cooking_recipes/new.xml
  def new
    @cooking_recipe = CookingRecipe.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @cooking_recipe }
    end
  end

  # GET /cooking_recipes/1/edit
  def edit
    @cooking_recipe = CookingRecipe.find(params[:id])
  end

  # POST /cooking_recipes
  # POST /cooking_recipes.xml
  def create
    @cooking_recipe = CookingRecipe.new(params[:cooking_recipe])

    respond_to do |format|
      if @cooking_recipe.save
        format.html { redirect_to(@cooking_recipe, :notice => 'CookingRecipe was successfully created.') }
        format.xml  { render :xml => @cooking_recipe, :status => :created, :location => @cooking_recipe }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @cooking_recipe.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /cooking_recipes/1
  # PUT /cooking_recipes/1.xml
  def update
    @cooking_recipe = CookingRecipe.find(params[:id])

    respond_to do |format|
      if @cooking_recipe.update_attributes(params[:cooking_recipe])
        format.html { redirect_to(@cooking_recipe, :notice => 'CookingRecipe was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @cooking_recipe.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /cooking_recipes/1
  # DELETE /cooking_recipes/1.xml
  def destroy
    @cooking_recipe = CookingRecipe.find(params[:id])
    @cooking_recipe.destroy

    respond_to do |format|
      format.html { redirect_to(cooking_recipes_url) }
      format.xml  { head :ok }
    end
  end

  private

  def convert_difficult_to_i
    params[:cooking_recipe][:difficult] = params[:cooking_recipe][:difficult].to_i if params[:cooking_recipe].has_key? :difficult
    logger.info params[:cooking_recipe][:difficult].class
  end
end

app/helpers/cooking_recipes_helper.rb
# -*- encoding : utf-8 -*-
module CookingRecipesHelper
end

app/views/cooking_recipes/edit.html.erb
<h1>Editing cooking_recipe</h1>

<%= form_for(@cooking_recipe) do |f| %>
    <%= f.error_messages %>

    <p>
      <%= f.label :name %><br/>
      <%= f.text_field :name %>
    </p>
    <p>
      <%= f.label :difficult %>
      <%= f.select :difficult, CookingRecipe.difficulties.each_with_index.collect { |d, i| [d, i] } %>
    </p>
    <p>
      <%= f.label :howto_prepare %><br/>
      <%= f.text_area :howto_prepare %>
    </p>

    <fieldset>
      <legend>Ingredientes (<%= link_to "adicionar", new_cooking_recipe_cooking_ingredient_path(@cooking_recipe) %>)</legend>

      <table>
        <thead>
        <tr>
          <th>Nome</th>
          <th>Quantidade</th>
          <th>Unidade</th>
        </tr>
        </thead>

        <tbody>
        <% for ingredient in @cooking_recipe.ingredients %>
        <tr>
          <td><%= ingredient.description %></td>
          <td><%= ingredient.unit %></td>
        </tr>
        <% end %>
        </tbody>
      </table>
    </fieldset>

    <p>
      <%= f.submit 'Update' %>
      <%= link_to 'Back', cooking_recipes_path %>
    </p>
<% end %>

app/views/cooking_recipes/index.html.erb
<%= render :partial => 'shared/title' %>

<table>
  <tr>
    <th>Name</th>
    <th>Dificuldade</th>
  </tr>

<% @cooking_recipes.each do |cooking_recipe| %>
  <tr>
    <td><%=h cooking_recipe.name %></td>
    <td><%=h cooking_recipe.difficult %></td>
    <td><%= link_to 'Show', cooking_recipe %></td>
    <td><%= link_to 'Edit', edit_cooking_recipe_path(cooking_recipe) %></td>
    <td><%= link_to 'Destroy', cooking_recipe, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'Nova receita', new_cooking_recipe_path %>
<%= link_to 'Novo ingredient', new_cooking_ingredient_path %>

app/views/cooking_recipes/new.html.erb
<%= render :partial => 'shared/title' %>

<%= form_for(@cooking_recipe) do |f| %>
    <%= f.error_messages %>

    <p>
      <%= f.label :name %><br/>
      <%= f.text_field :name %>
    </p>
    <p>
      <%= f.label :difficult %>
      <%= f.select :difficult, CookingRecipe.difficulties.each_with_index.collect {|d,i| [d,i]} %>
    </p>
    <p>
      <%= f.label :howto_prepare %><br/>
      <%= f.text_area :howto_prepare %>
    </p>
    <p>
      <%= f.submit 'Create' %>
      <%= link_to 'Back', cooking_recipes_path %>
    </p>
<% end %>

app/views/cooking_recipes/show.html.erb
<p>
  <b>Name:</b>
  <%=h @cooking_recipe.name %>
</p>

<p>
  <b>Howto prepare:</b>
  <%=h @cooking_recipe.howto_prepare %>
</p>

<p>
  <b>Dificult:</b>
  <%=h @cooking_recipe.difficult %>
</p>


<%= link_to 'Edit', edit_cooking_recipe_path(@cooking_recipe) %> |
<%= link_to 'Back', cooking_recipes_path %>