config/routes.rb
# -*- encoding : utf-8 -*-
Objectbox::Application.routes.draw do
  resources :alerts
  resources :cooking_ingredients
  resources :cooking_recipes do
    resources :cooking_ingredients
  end

  resources :simpletexts
  resources :postits
  resources :boards do
    resources :postits
  end

  resources :users
  resource :session

  match 'boards/:id' => 'boards#update', :method => :post
  match '/search' => 'search#index', :as => :search
  match 'search/:q' => 'search#index'
  match '/logout' => 'sessions#destroy', :as => :logout
  match '/login' => 'sessions#new', :as => :login
  match '/register' => 'users#create', :as => :register
  match '/signup' => 'users#new', :as => :signup
  match '/activate/:activation_code' => 'users#activate', :as => :activate
  match '/myprofile' => 'users#myprofile', :as => :myprofile
  match '/:controller(/:action(/:id))'

  root :to => 'object_collection#index'

end

app/models/postit.rb
# -*- encoding : utf-8 -*-
class Postit < ActiveRecord::Base
  acts_as_possession

  belongs_to :board

  def to_s
    self.title
  end

  def self.icon
    "document_64.png"
  end
end

app/controllers/postits_controller.rb
# -*- encoding : utf-8 -*-
class PostitsController < ApplicationController
  before_filter :load_postit, :only => [:show, :edit]

  def index
      @board  = Board.find(params[:board_id])
      redirect_to @board
  rescue ActiveRecord::RecordNotFound
    redirect_to :boards
  end

  def show
  end

  def edit
    redirect_to edit_board_path(@postit.board) + "#postit-#{@postit.id}"
  end

  private
  def load_postit
    @postit = Postit.find(params[:id])
  end
end

app/helpers/postits_helper.rb
# -*- encoding : utf-8 -*-
module PostitsHelper
end

app/views/postits/edit.html.erb
<h1>Editing postit</h1>

<%= form_for(@postit) do |f| %>
  <%= f.error_messages %>

  <p>
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </p>
  <p>
    <%= f.label :content %><br />
    <%= f.text_area :content %>
  </p>
  <p>
    <%= f.label :author %><br />
    <%= f.text_field :author %>
  </p>
  <p>
    <%= f.submit 'Update' %>
  </p>
<% end %>

<%= link_to 'Show', @postit %> |
<%= link_to 'Back', postits_path %>

app/views/postits/index.html.erb
<h1>Listing postits</h1>

<table>
  <tr>
    <th>Title</th>
    <th>Content</th>
    <th>Author</th>
  </tr>

<% @postits.each do |postit| %>
  <tr>
    <td><%=h postit.title %></td>
    <td><%=h postit.content %></td>
    <td><%=h postit.author %></td>
    <td><%= link_to 'Show', postit %></td>
    <td><%= link_to 'Edit', edit_postit_path(postit) %></td>
    <td><%= link_to 'Destroy', postit, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New postit', new_postit_path %>

app/views/postits/new.html.erb
<h1>New postit</h1>

<%= form_for(@postit) do |f| %>
  <%= f.error_messages %>

  <p>
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </p>
  <p>
    <%= f.label :content %><br />
    <%= f.text_area :content %>
  </p>
  <p>
    <%= f.label :author %><br />
    <%= f.text_field :author %>
  </p>
  <p>
    <%= f.submit 'Create' %>
  </p>
<% end %>

<%= link_to 'Back', postits_path %>

app/views/postits/show.html.erb
<p>
  <b>Title:</b>
  <%=h @postit.title %>
</p>

<p>
  <b>Content:</b>
  <%=h @postit.content %>
</p>

<p>
  <b>Author:</b>
  <%=h @postit.author %>
</p>


<%= link_to 'Edit', edit_postit_path(@postit) %> |
<%= link_to 'Back', postits_path %>