config/routes.rb
# -*- encoding : utf-8 -*-
Objectbox::Application.routes.draw do
  resources :alerts
  resources :cooking_ingredients
  resources :cooking_recipes do
    resources :cooking_ingredients
  end

  resources :simpletexts
  resources :postits
  resources :boards do
    resources :postits
  end

  resources :users
  resource :session

  match 'boards/:id' => 'boards#update', :method => :post
  match '/search' => 'search#index', :as => :search
  match 'search/:q' => 'search#index'
  match '/logout' => 'sessions#destroy', :as => :logout
  match '/login' => 'sessions#new', :as => :login
  match '/register' => 'users#create', :as => :register
  match '/signup' => 'users#new', :as => :signup
  match '/activate/:activation_code' => 'users#activate', :as => :activate
  match '/myprofile' => 'users#myprofile', :as => :myprofile
  match '/:controller(/:action(/:id))'

  root :to => 'object_collection#index'

end

app/models/alert.rb
# -*- encoding : utf-8 -*-
class Alert < ActiveRecord::Base
  acts_as_possession

  validates_presence_of :content

  def to_s
    read_attribute :content
  end

  def self.icon
    "alarm-icon.png"
  end
end

app/controllers/alerts_controller.rb
# -*- encoding : utf-8 -*-
class AlertsController < ApplicationController
  # GET /alerts
  # GET /alerts.xml
  def index
    @alerts = Alert.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @alerts }
    end
  end

  # GET /alerts/1
  # GET /alerts/1.xml
  def show
    @alert = Alert.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @alert }
    end
  end

  # GET /alerts/new
  # GET /alerts/new.xml
  def new
    @alert = Alert.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @alert }
    end
  end

  # GET /alerts/1/edit
  def edit
    @alert = Alert.find(params[:id])
  end

  # POST /alerts
  # POST /alerts.xml
  def create
    @alert = Alert.new(params[:alert])

    respond_to do |format|
      if @alert.save
        format.html { redirect_to(@alert, :notice => 'Alert was successfully created.') }
        format.xml  { render :xml => @alert, :status => :created, :location => @alert }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @alert.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /alerts/1
  # PUT /alerts/1.xml
  def update
    @alert = Alert.find(params[:id])

    respond_to do |format|
      if @alert.update_attributes(params[:alert])
        format.html { redirect_to(@alert, :notice => 'Alert was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @alert.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /alerts/1
  # DELETE /alerts/1.xml
  def destroy
    @alert = Alert.find(params[:id])
    @alert.destroy

    respond_to do |format|
      format.html { redirect_to(alerts_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/alerts_helper.rb
# -*- encoding : utf-8 -*-
module AlertsHelper
end

app/views/alerts/edit.html.erb
<h1>Editing alert</h1>

<%= form_for(@alert) do |f| %>
  <%= f.error_messages %>

  <p>
    <%= f.label :content %><br />
    <%= f.text_field :content %>
  </p>
  <p>
    <%= f.label :alert_date %><br />
    <%= f.date_select :alert_date %>
  </p>
  <p>
    <%= f.submit 'Update' %>
  </p>
<% end %>

<%= link_to 'Show', @alert %> |
<%= link_to 'Back', alerts_path %>

app/views/alerts/index.html.erb
<%= javascript_include_tag 'cal/mooECal' %>
<%= stylesheet_link_tag 'cal/mooECal' %>
<%= stylesheet_link_tag 'cal/mooECalSmall' %>
<%= stylesheet_link_tag 'cal/mooECalLarge' %>

<script type="text/javascript">
window.addEvent('domready', function() {
  new Calendar({calContainer:'calBody', scroller : false,
    cEvents: [
    <% @alerts.each do |alert| %>
    {
      title: '<%= link_to alert.content, alert %>',
      start: '<%= alert.alert_date.strftime('%Y-%m-%d') %>',
      end: '<%=h alert.alert_date.strftime('%Y-%m-%d') %>',
      'location': ''
    },
    <% end %>
    { start: ''}
    ]
  });
});
</script>

<h1>
  <%= image_tag current_model_icon, :size => '32x32' %> Alerts
  <%= link_to 'New event', new_alert_path, :style => 'font-size: 12px' %>
</h1>

<div id="calBody"></div>

app/views/alerts/new.html.erb
<h1>New alert</h1>

<%= form_for(@alert) do |f| %>
  <%= f.error_messages %>

  <p>
    <%= f.label :content %><br />
    <%= f.text_field :content %>
  </p>
  <p>
    <%= f.label :alert_date %><br />
    <%= f.date_select :alert_date %>
  </p>
  <p>
    <%= f.submit 'Create' %>
  </p>
<% end %>

<%= link_to 'Back', alerts_path %>

app/views/alerts/show.html.erb
<p>
  <b>Content:</b>
  <%=h @alert.content %>
</p>

<p>
  <b>Alert date:</b>
  <%=h @alert.alert_date %>
</p>


<%= link_to 'Edit', edit_alert_path(@alert) %> |
<%= link_to 'Back', alerts_path %>